---
branches:
  - master
  - next-major
projects:
  Middleware:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
      - src: AID-LEARNING/libmongodm/libmongodm
        version: ^0.0.1
      - src: AID-LEARNING/libredis/libredis
        version: ^0.0.1
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
      - src: AID-LEARNING/ExtraEvent/libEventAttribute
        version: ^1.0.2
        branch: pm5
      - src: AID-LEARNING/libExtraPath/libExtraPathConfig
        version: ^1.0.1
        branch: pm5
...
